#!/usr/bin/env ruby
# Security Regression Tests for bwilliams003.github.io
# Generated by Kindo AI Security Bot — 2026-02-22 v9
# Run with: bundle exec ruby test/security_test.rb
#
# These tests verify that security fixes remain in place
# and that vulnerable dependency versions are not re-introduced.
# Each test documents the CVE/GHSA it protects against.
#
# CHANGELOG v9:
#   - Added test_rexml_not_vulnerable_to_cve_2025_58767 (GHSA-c2f4-jgmc-q2r5)
#   - Updated test_rexml_not_vulnerable_to_dos to validate >= 3.4.2 floor
#   - Total: 16 tests (was 15 in v8)

require 'test/unit'
require 'rubygems'

class SecurityRegressionTest < Test::Unit::TestCase

  # ============================================================
  # SCA TESTS — Verify safe dependency version constraints
  # Covers: OSV.dev scan results (2026-02-22 v9)
  # ============================================================

  def test_jekyll_not_vulnerable_to_directory_traversal
    # GHSA-4xjh-m3qx-49wc | CVE-2018-17567 | CVSS 7.5 HIGH
    # Jekyll < 3.6.3/3.7.4/3.8.4 allows symlink directory traversal
    # Attackers can read arbitrary files by specifying symlinks on the dev server
    # OWASP A01:2021 — Broken Access Control
    gemfile = File.read('Gemfile')
    assert_match(/gem 'jekyll'.*>=.*4/, gemfile,
      "Jekyll must be pinned to >= 4.3.4 to remediate GHSA-4xjh-m3qx-49wc (directory traversal)")
  end

  def test_kramdown_not_vulnerable_to_rce
    # GHSA-52p9-v744-mwjj | CVE-2021-28834 | CVSS 9.8 CRITICAL
    # kramdown < 2.3.1 allows remote code execution via template injection
    # The convert_p method in the HTML parser does not properly sanitize input
    # OWASP A03:2021 — Injection
    gemfile = File.read('Gemfile')
    assert_match(/gem 'kramdown'.*>=.*2\.3\.1/, gemfile,
      "kramdown must be pinned to >= 2.3.1 to remediate GHSA-52p9-v744-mwjj (RCE)")
  end

  def test_kramdown_not_vulnerable_to_unintended_read
    # GHSA-mqm2-cgpr-p4m6 | CVE-2020-14001 | CVSS 9.8 CRITICAL
    # kramdown < 2.3.0 allows unintended file read via template injection
    # Files outside the Jekyll site scope can be read by attackers
    # OWASP A03:2021 — Injection
    gemfile = File.read('Gemfile')
    # Same >= 2.3.1 pin covers both CVEs
    assert_match(/gem 'kramdown'.*>=.*2\.3\.[1-9]/, gemfile,
      "kramdown must be pinned to >= 2.3.1 to also remediate GHSA-mqm2-cgpr-p4m6")
  end

  def test_addressable_not_vulnerable_to_redos
    # GHSA-jxhc-q857-3j6g | CVE-2021-32740 | CVSS 7.5 HIGH
    # Uncontrolled regex complexity in URI template parsing enables DoS
    # Crafted URIs can cause catastrophic backtracking in the regex engine
    # OWASP A06:2021 — Vulnerable and Outdated Components
    gemfile = File.read('Gemfile')
    assert_match(/gem 'addressable'.*>=.*2\.8/, gemfile,
      "addressable must be pinned to >= 2.8.0 to remediate GHSA-jxhc-q857-3j6g (ReDoS)")
  end

  def test_nokogiri_pinned_to_safe_version
    # Multiple CVEs in nokogiri/libxml2/libxslt (47 total as of 2026-02-22)
    # Including: GHSA-353f-x4gh-cqq8 (CRITICAL), GHSA-2rr5-8q37-2w7h (HIGH XXE)
    # Fixed in nokogiri >= 1.18.9 (latest patched release)
    # OWASP A06:2021 — Vulnerable and Outdated Components
    gemfile = File.read('Gemfile')
    assert_match(/gem 'nokogiri'.*>=.*1\.1[89]/, gemfile,
      "nokogiri must be explicitly pinned to >= 1.18.9 to remediate 47+ libxml2/libxslt CVEs")
  end

  def test_rexml_not_vulnerable_to_redos
    # GHSA-2rxp-v6pw-ch6m | CVE-2024-49761 | MODERATE
    # REXML < 3.3.9 has uncontrolled regex complexity in XML attribute parsing
    # Malformed XML input can cause catastrophic regex backtracking (DoS)
    # OWASP A06:2021 — Vulnerable and Outdated Components
    # NEW in v8: rexml was not pinned in previous remediation versions
    # v9: covered by >= 3.4.2 which supersedes >= 3.3.9
    gemfile = File.read('Gemfile')
    version_match = gemfile.match(/gem 'rexml'.*>=\s*(\d+)\.(\d+)\.(\d+)/)
    assert_not_nil(version_match, "rexml must be version-constrained")
    if version_match
      major, minor, patch = version_match[1..3].map(&:to_i)
      # >= 3.3.9 required for CVE-2024-49761; >= 3.4.2 used in v9
      is_safe = (major > 3) || (major == 3 && minor > 3) || (major == 3 && minor == 3 && patch >= 9)
      assert(is_safe,
        "rexml version #{version_match[0]} is too old for GHSA-2rxp-v6pw-ch6m — need >= 3.3.9")
    end
  end

  def test_rexml_not_vulnerable_to_dos
    # GHSA-4xqq-m2hx-25v8 | CVE-2024-39908 | MODERATE — DoS in element parsing (fixed 3.3.6)
    # GHSA-5866-49gr-22v4 | CVE-2024-41946 | MODERATE — DoS in proc instr parsing (fixed 3.3.6)
    # GHSA-r55c-59qm-vjw6 | CVE-2024-41123 | MODERATE — DoS vulnerability (fixed 3.3.3)
    # GHSA-vg3r-rm7w-2xgh | CVE-2024-35176 | MODERATE — DoS vulnerability (fixed 3.2.7)
    # GHSA-vmwr-mc7x-5vc3 | CVE-2024-43398 | MODERATE — DoS vulnerability (fixed 3.3.6)
    # GHSA-8cr8-4vfw-mr7h | CVE-2021-28965 | HIGH   — round-trip instability (fixed 3.2.5)
    # All covered by >= 3.4.2 (v9 minimum)
    # OWASP A06:2021 — Vulnerable and Outdated Components
    gemfile = File.read('Gemfile')
    version_match = gemfile.match(/gem 'rexml'.*>=\s*(\d+)\.(\d+)\.(\d+)/)
    assert_not_nil(version_match,
      "rexml must be explicitly version-constrained in Gemfile")
    if version_match
      major, minor, patch = version_match[1..3].map(&:to_i)
      # >= 3.4.2 required for full DoS protection including CVE-2025-58767
      is_safe = (major > 3) || (major == 3 && minor > 4) || (major == 3 && minor == 4 && patch >= 2)
      assert(is_safe,
        "rexml #{version_match[0]} is insufficient — need >= 3.4.2 for full protection (CVE-2025-58767 introduced in 3.3.3)")
    end
  end

  def test_rexml_not_vulnerable_to_cve_2025_58767
    # GHSA-c2f4-jgmc-q2r5 | CVE-2025-58767 | MODERATE — NEW in v9
    # REXML DoS condition when parsing malformed XML files
    # CRITICAL: This CVE was INTRODUCED in rexml 3.3.3 and fixed in 3.4.2
    # The v8 pin of >= 3.3.9 was within the VULNERABLE range!
    # Bundler resolving rexml 3.3.x satisfies >= 3.3.9 but remains exposed
    # OWASP A06:2021 — Vulnerable and Outdated Components
    gemfile = File.read('Gemfile')
    version_match = gemfile.match(/gem 'rexml'.*>=\s*(\d+)\.(\d+)\.(\d+)/)
    assert_not_nil(version_match,
      "rexml must be version-constrained to prevent CVE-2025-58767 (DoS in malformed XML)")
    if version_match
      major, minor, patch = version_match[1..3].map(&:to_i)
      # Must be >= 3.4.2 to avoid CVE-2025-58767 (introduced 3.3.3, fixed 3.4.2)
      is_safe = (major > 3) || (major == 3 && minor > 4) || (major == 3 && minor == 4 && patch >= 2)
      assert(is_safe,
        "GHSA-c2f4-jgmc-q2r5 (CVE-2025-58767): rexml >= 3.4.2 required — current constraint #{version_match[0]} allows vulnerable 3.3.x versions")
    end
  end

  # ============================================================
  # SAST/CONFIG TESTS — Verify credential safety
  # ============================================================

  def test_no_hardcoded_oauth_credentials
    # CWE-798: Use of Hard-coded Credentials
    # OWASP A02:2021 — Cryptographic Failures
    # Public repo exposure of OAuth credentials allows unauthorized API access
    config = File.read('_config.yml')
    
    # Check that client_id is not populated with actual credentials (10+ char alphanumeric)
    id_match = config.match(/gitalk_client_id:\s*\"(\w{10,})\"/)
    assert_nil(id_match, 
      "gitalk_client_id contains what appears to be a hardcoded credential — use GitHub Secrets")
    
    secret_match = config.match(/gitalk_client_secret:\s*\"(\w{10,})\"/)
    assert_nil(secret_match,
      "gitalk_client_secret contains what appears to be a hardcoded credential — use GitHub Secrets")
  end

  def test_config_references_secure_credential_storage
    # Verify security guidance is present near credential fields
    # Prevents future developers from accidentally adding credentials
    config = File.read('_config.yml')
    assert_match(/GitHub Secrets|github\.com\/secrets|encrypted-secrets/i, config,
      "Config should reference secure credential storage (GitHub Secrets) near credential fields")
  end

  def test_no_http_urls_in_config
    # OWASP A02:2021 — Cryptographic Failures (unencrypted transport)
    # HTTP URLs in config could allow MITM attacks during site generation
    config = File.read('_config.yml')
    http_urls = config.scan(/http:\/\/[^\s#]+/)
    # Filter out commented-out URLs
    non_comment_http = http_urls.reject { |url| url.start_with?('#') }
    assert_empty(non_comment_http,
      "Found insecure HTTP URLs in _config.yml: #{non_comment_http}. Use HTTPS.")
  end

  # ============================================================
  # IaC TESTS — Infrastructure configuration hardening
  # Validates security guidance documentation is present
  # ============================================================

  def test_csp_guidance_present
    # IaC-001 | HIGH | OWASP A05:2021 — Security Misconfiguration
    # Content Security Policy prevents XSS and data injection attacks
    # GitHub Pages does not support native CSP headers; guidance must direct devs to CDN layer
    config = File.read('_config.yml')
    assert_match(/Content.Security.Policy|CSP/i, config,
      "Config should document CSP implementation guidance (IaC-001: HIGH severity finding)")
  end

  def test_https_enforcement_guidance_present
    # IaC-003 | HIGH | OWASP A02:2021 — Cryptographic Failures
    # HSTS, X-Frame-Options prevent protocol downgrade and clickjacking attacks
    config = File.read('_config.yml')
    assert_match(/Strict.Transport.Security|HSTS|X-Frame-Options/i, config,
      "Config should document HTTPS enforcement headers (IaC-003: HIGH severity finding)")
  end

  def test_font_awesome_sri_guidance
    # IaC-002 | MEDIUM | OWASP A08:2021 — Software and Data Integrity Failures
    # CDN assets without SRI can be tampered with in transit or at the CDN
    config = File.read('_config.yml')
    assert_match(/SRI|Subresource.Integrity|fontawesome\.com\/kits|restrict.*domain/i, config,
      "Config should document FontAwesome CDN domain restriction (IaC-002: MEDIUM severity finding)")
  end

  def test_security_txt_reference_present
    # SAST-005 | INFO | OWASP A05:2021 — Security Misconfiguration
    # security.txt standard (RFC 9116) provides a discoverable security contact
    config = File.read('_config.yml')
    assert_match(/security\.txt|well-known|responsible.disclosure/i, config,
      "Config should reference security.txt for vulnerability disclosure (SAST-005: INFO)")
  end

  # ============================================================
  # IaC REGRESSION TESTS — Dependency hygiene
  # ============================================================

  def test_security_gemfile_is_not_empty
    # Regression: ensure Gemfile was not accidentally cleared or truncated
    # A cleared Gemfile would allow vulnerable version resolution
    gemfile = File.read('Gemfile')
    assert_operator(gemfile.length, :>, 200,
      "Gemfile appears to be nearly empty — security pins may have been removed")
  end

  def test_gemfile_has_pinned_versions
    # Ensure explicit version constraints exist
    # Unpinned dependencies allow Bundler to resolve vulnerable versions
    gemfile = File.read('Gemfile')
    assert_match(/>=\s*[\d\.]+/, gemfile,
      "Gemfile must have explicit version constraints to prevent vulnerable version resolution")
  end

  def test_gemfile_source_is_https
    # OWASP A08:2021 — Software and Data Integrity Failures
    # Gemfile source should use HTTPS to prevent MITM during gem downloads
    gemfile = File.read('Gemfile')
    assert_match(/source\s+"https:\/\/rubygems\.org"/, gemfile,
      "Gemfile source must use HTTPS (https://rubygems.org) to prevent MITM attacks")
  end

  def test_gemfile_has_all_required_security_pins
    # Regression: Verify all 5 required security pins are present
    # Removing any pin re-introduces the associated vulnerabilities
    gemfile = File.read('Gemfile')
    required_gems = ['jekyll', 'kramdown', 'addressable', 'nokogiri', 'rexml']
    required_gems.each do |gem_name|
      assert_match(/gem '#{gem_name}'.*>=/, gemfile,
        "#{gem_name} must have a minimum version constraint — its removal re-introduces CVEs")
    end
  end

end
