#!/usr/bin/env ruby
# Security Regression Tests for bwilliams003.github.io
# Generated by Kindo AI Security Bot — 2026-02-22
# Run with: bundle exec ruby test/security_test.rb
#
# These tests verify that security fixes remain in place
# and that vulnerable dependency versions are not re-introduced.

require 'test/unit'
require 'rubygems'

class SecurityRegressionTest < Test::Unit::TestCase

  # ============================================================
  # SCA TESTS — Verify safe dependency version constraints
  # ============================================================

  def test_jekyll_not_vulnerable_to_directory_traversal
    # GHSA-4xjh-m3qx-49wc | CVE-2018-17567 | CVSS 7.5
    # Jekyll < 3.6.3/3.7.4/3.8.4 allows symlink directory traversal
    # Attackers can read arbitrary files by specifying symlinks on the dev server
    gemfile = File.read('Gemfile')
    assert_match(/gem 'jekyll'.*>=.*4/, gemfile,
      "Jekyll must be pinned to >= 4.3.4 to remediate GHSA-4xjh-m3qx-49wc (directory traversal)")
  end

  def test_kramdown_not_vulnerable_to_rce
    # GHSA-52p9-v744-mwjj | CVE-2021-28834 | CVSS 9.8 CRITICAL
    # kramdown < 2.3.1 allows remote code execution via template injection
    # The convert_p method in the HTML parser does not properly sanitize input
    gemfile = File.read('Gemfile')
    assert_match(/gem 'kramdown'.*>=.*2\.3\.1/, gemfile,
      "kramdown must be pinned to >= 2.3.1 to remediate GHSA-52p9-v744-mwjj (RCE)")
  end

  def test_kramdown_not_vulnerable_to_unintended_read
    # GHSA-mqm2-cgpr-p4m6 | CVE-2020-14001 | CVSS 9.8 CRITICAL
    # kramdown < 2.3.0 allows unintended file read via template injection
    # Files outside the Jekyll site scope can be read by attackers
    gemfile = File.read('Gemfile')
    # Same >= 2.3.1 pin covers both CVEs
    assert_match(/gem 'kramdown'.*>=.*2\.3\.[1-9]/, gemfile,
      "kramdown must be pinned to >= 2.3.1 to also remediate GHSA-mqm2-cgpr-p4m6")
  end

  def test_addressable_not_vulnerable_to_redos
    # GHSA-jxhc-q857-3j6g | ReDoS in Addressable | CVSS 7.5
    # Uncontrolled regex complexity in URI template parsing enables DoS
    # Crafted URIs can cause catastrophic backtracking in the regex engine
    gemfile = File.read('Gemfile')
    assert_match(/gem 'addressable'.*>=.*2\.8/, gemfile,
      "addressable must be pinned to >= 2.8.0 to remediate GHSA-jxhc-q857-3j6g (ReDoS)")
  end

  def test_nokogiri_pinned_to_safe_version
    # Multiple CVEs in nokogiri/libxml2/libxslt (40+ total)
    # Including: GHSA-353f-x4gh-cqq8, GHSA-5w6v-399v-w3cc, GHSA-wx95-c6cv-8532
    # Latest safe version: >= 1.19.1
    gemfile = File.read('Gemfile')
    assert_match(/gem 'nokogiri'/, gemfile,
      "nokogiri must be explicitly pinned to remediate transitive libxml2/libxslt CVEs")
  end

  # ============================================================
  # SAST/CONFIG TESTS — Verify credential safety
  # ============================================================

  def test_no_hardcoded_oauth_credentials
    # CWE-798: Use of Hard-coded Credentials
    # OWASP A02:2021 - Cryptographic Failures
    # Public repo exposure of OAuth credentials allows unauthorized API access
    config = File.read('_config.yml')
    
    # Check that client_id is not populated with actual credentials (10+ char alphanumeric)
    id_match = config.match(/gitalk_client_id:\s*"(\w{10,})"/)
    assert_nil(id_match, 
      "gitalk_client_id contains what appears to be a hardcoded credential — use GitHub Secrets")
    
    secret_match = config.match(/gitalk_client_secret:\s*"(\w{10,})"/)
    assert_nil(secret_match,
      "gitalk_client_secret contains what appears to be a hardcoded credential — use GitHub Secrets")
  end

  def test_config_references_secure_credential_storage
    # Verify security guidance is present near credential fields
    # Prevents future developers from accidentally adding credentials
    config = File.read('_config.yml')
    assert_match(/GitHub Secrets|github\.com\/secrets|encrypted-secrets/i, config,
      "Config should reference secure credential storage (GitHub Secrets) near credential fields")
  end

  def test_no_http_urls_in_config
    # OWASP A02:2021 - Cryptographic Failures (unencrypted transport)
    # HTTP URLs in config could allow MITM attacks during site generation
    config = File.read('_config.yml')
    http_urls = config.scan(/http:\/\/[^\s#]+/)
    # Filter out commented-out URLs
    non_comment_http = http_urls.reject { |url| url.start_with?('#') }
    assert_empty(non_comment_http,
      "Found insecure HTTP URLs in _config.yml: #{non_comment_http}. Use HTTPS.")
  end

  # ============================================================
  # IaC REGRESSION TESTS — Dependency hygiene
  # ============================================================

  def test_security_gemfile_is_not_empty
    # Regression: ensure Gemfile was not accidentally cleared or truncated
    # A cleared Gemfile would allow vulnerable version resolution
    gemfile = File.read('Gemfile')
    assert_operator(gemfile.length, :>, 100,
      "Gemfile appears to be nearly empty — security pins may have been removed")
  end

  def test_gemfile_has_pinned_versions
    # Ensure explicit version constraints exist
    # Unpinned dependencies allow Bundler to resolve vulnerable versions
    gemfile = File.read('Gemfile')
    assert_match(/>=\s*[\d\.]+/, gemfile,
      "Gemfile must have explicit version constraints to prevent vulnerable version resolution")
  end

  def test_gemfile_source_is_https
    # OWASP A08:2021 - Software and Data Integrity Failures
    # Gemfile source should use HTTPS to prevent MITM during gem downloads
    gemfile = File.read('Gemfile')
    assert_match(/source\s+"https:\/\/rubygems\.org"/, gemfile,
      "Gemfile source must use HTTPS (https://rubygems.org) to prevent MITM attacks")
  end

end
