# Security Scanning Workflow
# ============================================================
# SECURITY FIX [LOW] VULN-NO-CI-WORKFLOW:
# Paste this file as .github/workflows/security-scan.yml
# after enabling GitHub Actions on this repository.
# OWASP A05:2021 | SOC2 CC8.1 | PCI-DSS 6.4.2
# ============================================================

name: Security Scan

on:
  push:
    branches: [main, 'security/**']
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  gem-audit:
    name: "SCA: bundler-audit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - run: gem install bundler-audit && bundler-audit update
      - run: bundler-audit check

  csp-sri-check:
    name: "SAST: CSP & Dependency Version Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify CSP present
        run: |
          grep -q "Content-Security-Policy" _includes/head.html \
            && echo "CSP OK" || (echo "MISSING CSP" && exit 1)
      - name: Verify no vulnerable jQuery
        run: |
          ! grep -E "jquery-(1|2|3\.[0-5])\." _includes/head.html \
            && echo "jQuery OK" || (echo "VULNERABLE jQuery" && exit 1)
      - name: Verify single jQuery load
        run: |
          COUNT=$(grep -c "jquery.*min\.js" _includes/head.html || true)
          [ "$COUNT" -le 1 ] && echo "jQuery dedup OK" || (echo "DUPLICATE jQuery" && exit 1)
      - name: Verify Bootstrap 5+
        run: |
          ! grep -E "bootstrap@4\.[0-5]\." _includes/head.html \
            && echo "Bootstrap OK" || (echo "VULNERABLE Bootstrap" && exit 1)
      - name: Check for committed OAuth secrets
        run: |
          ! grep -E "gitalk_client_secret:\s+[a-f0-9]{20,}" _config.yml \
            && echo "Secrets OK" || (echo "OAUTH SECRET COMMITTED" && exit 1)
