source "https://rubygems.org"

# SECURITY REMEDIATION — 2026-02-22
# Auto-generated by Kindo AI Security Bot
# OSV.dev scan: 3 HIGH SCA vulns + 1 MEDIUM + transitive risks identified

# --- DIRECT DEPENDENCIES ---
# jekyll: pinned >= 4.3.4 to remediate GHSA-4xjh-m3qx-49wc (Directory Traversal, CVE-2018-17567)
# Security: Symlink traversal allows attackers to read arbitrary files via dev server
gem 'jekyll', '>= 4.3.4'

# kramdown: pinned >= 2.3.1 to remediate:
#   - GHSA-52p9-v744-mwjj (RCE in Kramdown, CVE-2021-28834, CVSS 9.8)
#   - GHSA-mqm2-cgpr-p4m6 (Unintended read/template injection, CVE-2020-14001, CVSS 9.8)
# Security: Remote code execution via template injection in convert_p HTML parser method
gem 'kramdown', '>= 2.3.1'

# addressable: pinned >= 2.8.0 to remediate:
#   - GHSA-jxhc-q857-3j6g (ReDoS in Addressable URI templates, CVSS 7.5)
# Security: Uncontrolled regex complexity enables denial of service via crafted URIs
gem 'addressable', '>= 2.8.0'

# nokogiri: pinned to latest to remediate 40+ transitive CVEs via libxml2/libxslt
# Latest fixes GHSA-353f-x4gh-cqq8, GHSA-5w6v-399v-w3cc, GHSA-wx95-c6cv-8532, etc.
gem 'nokogiri', '>= 1.19.1'

# --- JEKYLL PLUGINS ---
gem 'jekyll-feed'    # Blog RSS feed generator
gem 'jekyll-watch'   # File watching for development

# --- OWASP COMPLIANCE NOTES ---
# A01:2021 - Broken Access Control: jekyll >= 4.3.4 resolves symlink traversal
# A03:2021 - Injection: kramdown >= 2.3.1 resolves template injection/RCE
# A06:2021 - Vulnerable Components: All deps pinned to minimum safe versions
# A09:2021 - Logging: Consider adding jekyll-logging gem for audit trails
