source "https://rubygems.org"

# SECURITY REMEDIATION — 2026-02-22 v8
# Auto-generated by Kindo AI Security Bot
# Scan tools: OSV.dev API, SAST pattern analysis, IaC review
# OSV scan: 2 CRITICAL, 3 HIGH, 3 MODERATE vulnerabilities identified

# ============================================================
# DIRECT DEPENDENCIES — Security-pinned minimum versions
# ============================================================

# jekyll: pinned >= 4.3.4 to remediate:
#   GHSA-4xjh-m3qx-49wc | CVE-2018-17567 | CVSS 7.5 HIGH
#   Symlink traversal attack allows arbitrary file read via dev server
#   OWASP A01:2021 - Broken Access Control
gem 'jekyll', '>= 4.3.4'

# kramdown: pinned >= 2.3.1 to remediate TWO critical CVEs:
#   GHSA-mqm2-cgpr-p4m6 | CVE-2020-14001 | CVSS 9.8 CRITICAL
#   Unintended file read via template injection in HTML parser
#   GHSA-52p9-v744-mwjj | CVE-2021-28834 | CVSS 9.8 CRITICAL
#   Remote code execution via template injection in convert_p method
#   OWASP A03:2021 - Injection
gem 'kramdown', '>= 2.3.1'

# addressable: pinned >= 2.8.0 to remediate:
#   GHSA-jxhc-q857-3j6g | CVE-2021-32740 | CVSS 7.5 HIGH
#   ReDoS via uncontrolled regex complexity in URI template expansion
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'addressable', '>= 2.8.0'

# nokogiri: pinned >= 1.18.9 to remediate 47+ vulnerabilities including:
#   GHSA-353f-x4gh-cqq8 | CRITICAL — Multiple libxml2/libxslt CVEs
#   GHSA-2rr5-8q37-2w7h | CVE-2021-41098 | HIGH — XXE vulnerability
#   GHSA-242x-7cm6-4w8j | CVE-2019-18197 | HIGH — Use of uninitialized resource
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'nokogiri', '>= 1.18.9'

# rexml: pinned >= 3.3.9 to remediate ReDoS/DoS vulnerabilities:
#   GHSA-2rxp-v6pw-ch6m | CVE-2024-49761 | MODERATE — ReDoS in XML parsing
#   GHSA-4xqq-m2hx-25v8 | CVE-2024-39908 | MODERATE — DoS vulnerability
#   GHSA-5866-49gr-22v4 | CVE-2024-41946 | MODERATE — DoS vulnerability
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'rexml', '>= 3.3.9'

# ============================================================
# JEKYLL PLUGINS
# ============================================================
gem 'jekyll-feed'    # Blog RSS feed generator (no known vulnerabilities)
gem 'jekyll-watch'   # File watching for dev mode (no known vulnerabilities)

# ============================================================
# OWASP COMPLIANCE MAPPING
# ============================================================
# A01:2021 - Broken Access Control        -> jekyll >= 4.3.4 (CVE-2018-17567)
# A02:2021 - Cryptographic Failures       -> HTTPS-only gem source enforced
# A03:2021 - Injection                    -> kramdown >= 2.3.1 (CVE-2020-14001, CVE-2021-28834)
# A06:2021 - Vulnerable Components        -> All deps pinned to minimum safe versions
# A08:2021 - Software Integrity Failures  -> Explicit version constraints prevent resolution drift
# A09:2021 - Logging/Monitoring Failures  -> Consider adding jekyll-logging for audit trails
