source "https://rubygems.org"

# SECURITY REMEDIATION — 2026-02-22 v9
# Auto-generated by Kindo AI Security Bot
# Scan tools: OSV.dev API, SAST pattern analysis, IaC review
# OSV scan: 2 CRITICAL, 3 HIGH, 4 MODERATE vulnerabilities identified
#
# CHANGELOG from v8 -> v9:
#   Bumped rexml >= 3.4.2 to fix CVE-2025-58767 (DoS — introduced in 3.3.3, fixed in 3.4.2)
#   v8's >= 3.3.9 pin was WITHIN the vulnerable range (3.3.3 <= 3.3.9 < 3.4.2)

# ============================================================
# DIRECT DEPENDENCIES — Security-pinned minimum versions
# ============================================================

# jekyll: pinned >= 4.3.4 to remediate:
#   GHSA-4xjh-m3qx-49wc | CVE-2018-17567 | CVSS 7.5 HIGH
#   Symlink traversal attack allows arbitrary file read via dev server
#   OWASP A01:2021 - Broken Access Control
gem 'jekyll', '>= 4.3.4'

# kramdown: pinned >= 2.3.1 to remediate TWO critical CVEs:
#   GHSA-mqm2-cgpr-p4m6 | CVE-2020-14001 | CVSS 9.8 CRITICAL
#   Unintended file read via template injection in HTML parser
#   GHSA-52p9-v744-mwjj | CVE-2021-28834 | CVSS 9.8 CRITICAL
#   Remote code execution via template injection in convert_p method
#   OWASP A03:2021 - Injection
gem 'kramdown', '>= 2.3.1'

# addressable: pinned >= 2.8.0 to remediate:
#   GHSA-jxhc-q857-3j6g | CVE-2021-32740 | CVSS 7.5 HIGH
#   ReDoS via uncontrolled regex complexity in URI template expansion
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'addressable', '>= 2.8.0'

# nokogiri: pinned >= 1.18.9 to remediate 47+ vulnerabilities including:
#   GHSA-353f-x4gh-cqq8 | CRITICAL — Multiple libxml2/libxslt CVEs
#   GHSA-2rr5-8q37-2w7h | CVE-2021-41098 | HIGH — XXE vulnerability
#   GHSA-242x-7cm6-4w8j | CVE-2019-18197 | HIGH — Use of uninitialized resource
#   GHSA-5w6v-399v-w3cc | CVE-2025-32414/CVE-2025-32415 — libxml2 updates (fixed 1.18.8)
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'nokogiri', '>= 1.18.9'

# rexml: pinned >= 3.4.2 to remediate ALL 8 known rexml CVEs:
# [Carried forward from v8 — all still covered by >= 3.4.2]:
#   GHSA-2rxp-v6pw-ch6m | CVE-2024-49761 | MODERATE — ReDoS in XML attr parsing (fixed 3.3.9)
#   GHSA-4xqq-m2hx-25v8 | CVE-2024-39908 | MODERATE — DoS in element parsing (fixed 3.3.6)
#   GHSA-5866-49gr-22v4 | CVE-2024-41946 | MODERATE — DoS in proc instr parsing (fixed 3.3.6)
#   GHSA-r55c-59qm-vjw6 | CVE-2024-41123 | MODERATE — DoS vulnerability (fixed 3.3.3)
#   GHSA-vg3r-rm7w-2xgh | CVE-2024-35176 | MODERATE — DoS vulnerability (fixed 3.2.7)
#   GHSA-vmwr-mc7x-5vc3 | CVE-2024-43398 | MODERATE — DoS vulnerability (fixed 3.3.6)
#   GHSA-8cr8-4vfw-mr7h | CVE-2021-28965 | HIGH   — Round-trip instability (fixed 3.2.5)
# [v9 NEW FIX]:
#   GHSA-c2f4-jgmc-q2r5 | CVE-2025-58767 | MODERATE — DoS in malformed XML (fixed 3.4.2)
#   WARNING: This CVE was INTRODUCED in 3.3.3 — v8 pin of >= 3.3.9 was in the vulnerable range!
#   OWASP A06:2021 - Vulnerable and Outdated Components
gem 'rexml', '>= 3.4.2'

# ============================================================
# JEKYLL PLUGINS
# ============================================================
gem 'jekyll-feed'    # Blog RSS feed generator (no known vulnerabilities)
gem 'jekyll-watch'   # File watching for dev mode (no known vulnerabilities)

# ============================================================
# OWASP COMPLIANCE MAPPING
# ============================================================
# A01:2021 - Broken Access Control        -> jekyll >= 4.3.4 (CVE-2018-17567)
# A02:2021 - Cryptographic Failures       -> HTTPS-only gem source enforced
# A03:2021 - Injection                    -> kramdown >= 2.3.1 (CVE-2020-14001, CVE-2021-28834)
# A06:2021 - Vulnerable Components        -> All deps pinned to minimum safe versions
# A08:2021 - Software Integrity Failures  -> Explicit version constraints prevent resolution drift
# A09:2021 - Logging/Monitoring Failures  -> Consider adding jekyll-logging for audit trails
